############# English navigation ##############

# Main menu
[[main]]
name = "Home"
url = "preview/" # don't use a slash for home url
weight = 1

[[main]]
name = "About"
hasChildren = true
url = ""
weight = 2

[[main]]
parent = "About"
name = "About Us"
url = "about/"
weight = 1

[[main]]
parent = "About"
name = "Contact Us"
url = "contact/"
weight = 1

[[main]]
name = "Latest"
hasChildren = true
url = ""
weight = 3

[[main]]
parent = "Latest"
name = "News"
url = "news/"
weight = 1

[[main]]
parent = "Latest"
name = "Events Calendar"
url = "events/calendar/"
weight = 2

[[main]]
parent = "Latest"
name = "Partnership Meetings"
url = "events/partnership-meetings/"
weight = 3

[[main]]
parent = "Latest"
name = "Our Newsletter"
url = "newsletter/"
weight = 4

[[main]]
name = "Partners"
hasChildren = true
url = ""
weight = 4

[[main]]
parent = "Partners"
name = "Our Partners"
url = "partners/"
weight = 1

[[main]]
parent = "Partners"
name = "Partner Projects"
url = "projects/"
weight = 1

[[main]]
parent = "Partners"
name = "Partner Map"
url = "map/"
weight = 1

[[main]]
name = "Funding"
hasChildren = true
url = "funding/"
weight = 5

[[main]]
parent = "Funding"
name = "Small Grant Scheme"
url = "funding/small-grant-scheme/"
weight = 1


# Footer Menu

[[footer]]
name = "Contact Us"
url = "contact/"
weight = 1

[[footer]]
name = "Code of Conduct"
url = "conduct/"
weight = 2

[[footer]]
name = "Privacy"
url = "privacy/"
weight = 3

[[footer]]
name = "Licensing"
url = "licensing/"
weight = 4


