############# English navigation ##############

# Main menu
[[main]]
name = "Hafan"
url = "" # don't use a slash for home url
weight = 1

[[main]]
name = "Amdanom ni"
hasChildren = true
url = ""
weight = 2

[[main]]
parent = "Amdanom ni"
name = "Amdanom ni"
url = "about/"
weight = 1

[[main]]
parent = "Amdanom ni"
name = "Cysylltu â ni"
url = "contact/"
weight = 1

[[main]]
name = "Newyddion a digwyddiadau"
hasChildren = true
url = ""
weight = 3

[[main]]
parent = "Newyddion a digwyddiadau"
name = "Y newyddion diweddaraf"
url = "news/"
weight = 1

[[main]]
parent = "Newyddion a digwyddiadau"
name = "Calendr digwyddiadau"
url = "/events/calendar/"
weight = 2

[[main]]
parent = "Newyddion a digwyddiadau"
name = "Cyfarfodydd y Bartneriaeth"
url = "/events/partnership-meetings/"
weight = 3

[[main]]
parent = "Newyddion a digwyddiadau"
name = "Ein cylchlythyr"
url = "newsletter/"
weight = 4

[[main]]
name = "Partneriaid"
hasChildren = true
url = ""
weight = 4

[[main]]
parent = "Partneriaid"
name = "Ein partneriaid"
url = "partners/"
weight = 1

[[main]]
parent = "Partneriaid"
name = "Map o'r partneriaid"
url = "map/"
weight = 1

[[main]]
name = "Cyllid"
hasChildren = true
url = "funding/"
weight = 5

[[main]]
parent = "Cyllid"
name = "Cynllun Grantiau Bach"
url = "/funding/small-grant-scheme/"
weight = 1


# Footer Menu

[[footer]]
name = "Cysylltu â ni"
url = "contact/"
weight = 1

[[footer]]
name = "Cod Ymddygiad"
url = "conduct/"
weight = 2

[[footer]]
name = "Preifatrwydd"
url = "privacy/"
weight = 3

[[footer]]
name = "Trwyddedu"
url = "licensing/"
weight = 4
